#!/bin/bash

#Simple password generator 

echo "This is a simple password generator"

echo "Enter the length of the password you want: "
read PASS_LENGTH

echo "Enter the number of passwords you want"
read NUM_PASS

for ((i=1; i<=NUM_PASS; i++)); do
	password=$(openssl rand -base64 48 | cut -c1-$PASS_LENGTH)
	echo "Password $i: $password" 
done
